import {
  pgTable,
  bigint,
  text,
  integer,
  boolean,
  jsonb,
  timestamp,
  real,
} from "drizzle-orm/pg-core";

export const agenti = pgTable("agenti", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  orgId: text("org_id").notNull(),
  orgShortId: text("org_short_id"),
  userId: text("user_id").notNull(),
  nume: text("nume").notNull(),
  telefon: text("telefon"),
  email: text("email"),
  poza: text("poza"),
  zone: text("zone"),
  rol: text("rol").default("agent"),
  createdByName: text("created_by_name"),
  updatedByName: text("updated_by_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const clienti = pgTable("clienti", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  orgId: text("org_id").notNull(),
  orgShortId: text("org_short_id"),
  userId: text("user_id").notNull(),
  nume: text("nume").notNull(),
  telefon: text("telefon"),
  email: text("email"),
  buget: text("buget"),
  interes: text("interes"),
  zona: text("zona"),
  status: text("status").default("Nou"),
  sursa: text("sursa"),
  ultimaInteractiune: text("ultima_interactiune"),
  createdByName: text("created_by_name"),
  updatedByName: text("updated_by_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const proprietati = pgTable("proprietati", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  orgId: text("org_id").notNull(),
  orgShortId: text("org_short_id"),
  userId: text("user_id").notNull(),
  titlu: text("titlu").notNull(),
  tip: text("tip"),
  tipTranzactie: text("tip_tranzactie").default("vanzare"),
  pret: text("pret"),
  pretNumeric: real("pret_numeric"),
  negociabil: boolean("negociabil").default(false),
  badgeExclusivitate: boolean("badge_exclusivitate").default(false),
  badgeComisionZero: boolean("badge_comision_zero").default(false),
  descriere: text("descriere"),
  status: text("status").default("activ"),
  statusProprietate: text("status_proprietate").default("disponibil"),
  recomandata: boolean("recomandata").default(true),
  disponibilDin: text("disponibil_din"),
  agentId: text("agent_id"),
  imagine: text("imagine"),
  fotografii: jsonb("fotografii").default("[]"),
  adresa: jsonb("adresa").default("{}"),
  caracteristici: jsonb("caracteristici").default("{}"),
  dotari: jsonb("dotari").default("[]"),
  createdByName: text("created_by_name"),
  updatedByName: text("updated_by_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const programari = pgTable("programari", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  orgId: text("org_id").notNull(),
  orgShortId: text("org_short_id"),
  userId: text("user_id").notNull(),
  data: text("data"),
  ora: text("ora"),
  titlu: text("titlu").notNull(),
  client: text("client").notNull(),
  clientId: text("client_id"),
  telefon: text("telefon"),
  locatie: text("locatie"),
  tip: text("tip").default("Vizionare"),
  status: text("status").default("Confirmată"),
  observatii: text("observatii"),
  ultimaActualizare: text("ultima_actualizare"),
  createdByName: text("created_by_name"),
  updatedByName: text("updated_by_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const taskuri = pgTable("taskuri", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  orgId: text("org_id").notNull(),
  orgShortId: text("org_short_id"),
  userId: text("user_id").notNull(),
  titlu: text("titlu").notNull(),
  data: text("data"),
  prioritate: text("prioritate").default("medium"),
  status: text("status").default("pending"),
  createdByName: text("created_by_name"),
  updatedByName: text("updated_by_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const proiecte = pgTable("proiecte", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  orgId: text("org_id").notNull(),
  orgShortId: text("org_short_id"),
  userId: text("user_id").notNull(),
  nume: text("nume").notNull(),
  zona: text("zona").notNull(),
  descriere: text("descriere"),
  totalUnitati: integer("total_unitati"),
  disponibile: integer("disponibile"),
  stadii: text("stadii").default("planned"),
  pretDeLa: real("pret_de_la"),
  pretPanaLa: real("pret_pana_la"),
  dotari: text("dotari"),
  imagine: text("imagine"),
  document: text("document"),
  createdByName: text("created_by_name"),
  updatedByName: text("updated_by_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const documente = pgTable("documente", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  orgId: text("org_id").notNull(),
  orgShortId: text("org_short_id"),
  userId: text("user_id").notNull(),
  nume: text("nume").notNull(),
  tip: text("tip").default("Contract"),
  client: text("client"),
  proprietate: text("proprietate"),
  data: text("data"),
  fisier: text("fisier"),
  createdByName: text("created_by_name"),
  updatedByName: text("updated_by_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const comisioane = pgTable("comisioane", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  orgId: text("org_id").notNull(),
  orgShortId: text("org_short_id"),
  userId: text("user_id").notNull(),
  agent: text("agent").notNull(),
  proprietate: text("proprietate"),
  valoareTranzactie: text("valoare_tranzactie"),
  procent: text("procent"),
  suma: text("suma"),
  data: text("data"),
  status: text("status").default("În așteptare"),
  createdByName: text("created_by_name"),
  updatedByName: text("updated_by_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const campanii = pgTable("campanii", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  orgId: text("org_id").notNull(),
  orgShortId: text("org_short_id"),
  userId: text("user_id").notNull(),
  nume: text("nume").notNull(),
  tip: text("tip").default("Email"),
  dataStart: text("data_start"),
  dataEnd: text("data_end"),
  buget: text("buget"),
  createdByName: text("created_by_name"),
  updatedByName: text("updated_by_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const notificari = pgTable("notificari", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  orgId: text("org_id").notNull(),
  orgShortId: text("org_short_id"),
  userId: text("user_id").notNull(),
  cheie: text("cheie"),
  tip: text("tip").default("info"),
  titlu: text("titlu").notNull(),
  mesaj: text("mesaj"),
  prioritate: text("prioritate").default("normal"),
  citit: boolean("citit").default(false),
  createdByName: text("created_by_name"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const organizations = pgTable("organizations", {
  clerkId: text("clerk_id").notNull(),
  shortId: text("short_id"),
});
